name: "Render plugins site"

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        name: "Render plugins site"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Build static files
              id: build
              run: |
                  make all

            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                  path: html/

    deploy:
        if: github.event_name == 'push'  # only deploy when pushed to main.
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
