name: Validate new plugin

on:
    pull_request_target:
        types: [opened, reopened]
        paths:
            - 'plugins.json'
    push:
        paths:
            - 'plugins.json'
            - '.github/workflows/plugin-pr-validate.yml'
            - 'scripts/lint-metadata.py'
            - 'scripts/extract-modified-json.py'
            - 'scripts/validateall.sh'

permissions:
    contents: read
    pull-requests: write

jobs:
    start-plugin-contrib-pr:
        runs-on: ubuntu-latest
        env:
            PR_NUMBER: ${{ github.event.pull_request.number }}
            REPO: ${{ github.repository }}
            GH_TOKEN: ${{ github.token }}
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v6
              with:
                  python-version: "3.14"
                  cache: "pip"
                  python-version-file: ".python-version"

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

            - name: Extract the new plugin data and lint it
              shell: bash
              run: |
                  set -ex  # fail script on first command failure.

                  FORK_USER=$(gh pr view $PR_NUMBER --repo=$REPO --json author | jq -r .author.login)
                  FORK_REPO=$(gh pr view $PR_NUMBER --repo=$REPO --json headRepository | jq -r .headRepository.name)
                  FORK_BRANCH=$(gh pr view $PR_NUMBER --repo=$REPO --json headRefName | jq -r .headRefName)
                  scripts/validateall.sh "$FORK_USER" "$FORK_REPO" "$FORK_BRANCH"
