name: Validate new plugin

on:
    pull_request:
        types: [opened, reopened]
        paths:
            - 'plugins.json'
    push:
        paths:
            - 'plugins.json'
            - '.github/workflows/plugin-pr-validate.yml'

permissions:
    contents: read
    pull-requests: write

jobs:
    start-plugin-contrib-pr:
        runs-on: ubuntu-latest
        env:
            PR_NUMBER: ${{ github.event.number }}
            REPO: ${{ github.repository }}
            GH_TOKEN: ${{ github.token }}
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v6
              with:
                  python-version: "3.14"
                  cache: "pip"
                  python-version-file: ".python-version"

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

            - name: Extract the new plugin data and lint it
              shell: bash
              run: |
                  set -ex  # fail script on first command failure.

                  # Extract the new plugin information from plugins.json
                  NEW_PLUGIN_DATA=new_plugin.json
                  uv run scripts/extract-modified-json.py \
                    plugins.json \
                    main \
                    "$NEW_PLUGIN_DATA"

                  # clone the new repo
                  REPO_URL=$(cat "$NEW_PLUGIN_DATA" | jq --raw-output .repo_url)
                  LOCAL_REPO_DIR=repo
                  git clone "$REPO_URL" "$LOCAL_REPO_DIR"

                  # Lint things
                  LINT_RESULTS_FILE=lint_results.txt
                  uv run scripts/lint-metadata.py \
                    "${LOCAL_REPO_DIR}/pyproject.toml" \
                    "plugins.json" \
                    --target-file="$LINT_RESULTS_FILE"

                  # Post results to the PR for review
                  gh pr comment "$PR_NUMBER" --body-file="$LINT_RESULTS_FILE"
